require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dance_classes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # DanceClass. As you add validations to DanceClass, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DanceClass.create! valid_attributes
      get dance_classes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dance_class = DanceClass.create! valid_attributes
      get dance_class_url(dance_class)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dance_class_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      dance_class = DanceClass.create! valid_attributes
      get edit_dance_class_url(dance_class)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DanceClass" do
        expect {
          post dance_classes_url, params: { dance_class: valid_attributes }
        }.to change(DanceClass, :count).by(1)
      end

      it "redirects to the created dance_class" do
        post dance_classes_url, params: { dance_class: valid_attributes }
        expect(response).to redirect_to(dance_class_url(DanceClass.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DanceClass" do
        expect {
          post dance_classes_url, params: { dance_class: invalid_attributes }
        }.to change(DanceClass, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post dance_classes_url, params: { dance_class: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dance_class" do
        dance_class = DanceClass.create! valid_attributes
        patch dance_class_url(dance_class), params: { dance_class: new_attributes }
        dance_class.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dance_class" do
        dance_class = DanceClass.create! valid_attributes
        patch dance_class_url(dance_class), params: { dance_class: new_attributes }
        dance_class.reload
        expect(response).to redirect_to(dance_class_url(dance_class))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        dance_class = DanceClass.create! valid_attributes
        patch dance_class_url(dance_class), params: { dance_class: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dance_class" do
      dance_class = DanceClass.create! valid_attributes
      expect {
        delete dance_class_url(dance_class)
      }.to change(DanceClass, :count).by(-1)
    end

    it "redirects to the dance_classes list" do
      dance_class = DanceClass.create! valid_attributes
      delete dance_class_url(dance_class)
      expect(response).to redirect_to(dance_classes_url)
    end
  end
end
